import {useEffect,useMemo,useState} from 'react';
import {Card,Empty,PlayerTable} from './components';
import {Player,Settings,money,scoreClass,positionGroup} from './types';

export default function App(){
 const [tab,setTab]=useState<'dashboard'|'players'|'squad'|'settings'>('dashboard');
 const [players,setPlayers]=useState<Player[]>([]),[squad,setSquad]=useState<Player[]>([]);
 const [settings,setSettings]=useState<Settings>({transferBudget:65000,maxWeeklyWage:1000,formation:'4-2-3-1'});
 const [query,setQuery]=useState(''),[shortOnly,setShortOnly]=useState(false),[message,setMessage]=useState('');
 const [decision,setDecision]=useState<any>(null);
 const [busy,setBusy]=useState(true);
 const load=async()=>{try{const [targets,currentSquad,club]=await Promise.all([window.moneyball.listPlayers('targets'),window.moneyball.listPlayers('squad'),window.moneyball.getSettings()]);setPlayers(targets);setSquad(currentSquad);setSettings(club)}catch(e:any){setMessage('Daten konnten nicht geladen werden: '+(e.message||e))}};
 useEffect(()=>{load().finally(()=>setBusy(false))},[]);
 const importData=async(type:'targets'|'squad')=>{if(busy)return;setBusy(true);try{const r=await window.moneyball.importPlayers(type);if(!r.canceled){setMessage(`${r.rowCount} Spieler importiert${r.warnings?.length?' · '+r.warnings.join(' · '):''}`);await load()}}catch(e:any){setMessage('Importfehler: '+(e.message||e))}finally{setBusy(false)}};
 const filtered=useMemo(()=>players.filter(p=>(!shortOnly||p.shortlisted)&&`${p.name} ${p.club} ${p.position}`.toLowerCase().includes(query.toLowerCase())),[players,query,shortOnly]);
 const groups=useMemo(()=>{const x:Record<string,Player[]>={};squad.forEach(p=>{const k=positionGroup(p.position);(x[k]??=[]).push(p)});return Object.entries(x).map(([position,list])=>({position,count:list.length,avg:Math.round(list.reduce((a,p)=>a+p.scores.moneyball,0)/list.length)})).sort((a,b)=>a.avg-b.avg)},[squad]);
 const toggle=async(p:Player)=>{try{await window.moneyball.toggleShortlist(p.id);await load()}catch(e:any){setMessage('Shortlist konnte nicht geändert werden: '+(e.message||e))}};
 const decide=async(p:Player)=>{try{setDecision({player:p,data:await window.moneyball.transferDecision(p)})}catch(e:any){setMessage('Entscheidung konnte nicht berechnet werden: '+(e.message||e))}};
 const saveClub=async()=>{try{setSettings(await window.moneyball.saveSettings(settings));setMessage('Club-Budget gespeichert.')}catch(e:any){setMessage('Einstellungen konnten nicht gespeichert werden: '+(e.message||e))}};
 const backup=async()=>{try{const r=await window.moneyball.backup();if(!r.canceled)setMessage('Backup gespeichert.')}catch(e:any){setMessage('Backup fehlgeschlagen: '+(e.message||e))}};
 return <div className="app"><aside><div className="brand"><div className="logo">M</div><div><b>FM26</b><span>MONEYBALL HQ</span></div></div><nav>{[['dashboard','HQ Dashboard'],['players','Recruitment'],['squad','Squad Intelligence'],['settings','Club & Budget']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id as any)} key={id}>{label}</button>)}</nav><div className="asideFoot"><small>LOCAL DATABASE</small><b>● OFFLINE READY</b></div></aside><main aria-busy={busy}><header><div><h1>{tab==='dashboard'?'Recruitment Command Center':tab==='players'?'Player Intelligence':tab==='squad'?'Squad Intelligence':'Club & Budget'}</h1><p>{settings.formation} Moneyball recruitment · transparent & local</p></div><div className="actions"><button disabled={busy} onClick={()=>importData('squad')}>{busy?'Bitte warten…':'Kader importieren'}</button><button disabled={busy} className="primary" onClick={()=>importData('targets')}>+ Spieler importieren</button></div></header>{message&&<div className="notice" role="status"><span>{message}</span><button aria-label="Meldung schließen" onClick={()=>setMessage('')}>×</button></div>}
 {tab==='dashboard'&&<><section className="stats"><Card title="Analysierte Targets" value={String(players.length)} sub="aktueller Import"/><Card title="Hidden Gems" value={String(players.filter(p=>p.tags.includes('Hidden Gem')).length)} sub="automatisch erkannt"/><Card title="Shortlist" value={String(players.filter(p=>p.shortlisted).length)} sub="aktive Kandidaten"/><Card title="Transferbudget" value={money(settings.transferBudget)} sub={`${money(settings.maxWeeklyWage)}/W Wage cap`}/></section>{players.length?<section className="panel"><h2>Top Transfer Targets</h2><PlayerTable players={players.slice(0,5)} onToggle={toggle} onDecision={decide}/></section>:<Empty onImport={()=>importData('targets')}/>}<section className="grid2"><div className="panel"><h2>Kaderbedarf</h2>{groups.length?groups.slice(0,5).map(g=><div className="need" key={g.position}><b>{g.position}</b><span>{g.count} Spieler</span><strong className={scoreClass(g.avg)}>{g.avg}</strong></div>):<p className="muted">Importiere deinen Kader für Schwachstellen.</p>}</div><div className="panel"><h2>Score-Modell</h2><p className="muted">Fehlende Daten werden ausgelassen. Niedrige Confidence dämpft das Ergebnis zur neutralen Mitte und bleibt separat sichtbar.</p><div className="formula">30% Performance · 25% Value · 15% Financial · 15% Development · 10% Role Fit</div></div></section></>}
 {tab==='players'&&<section className="panel"><div className="toolbar"><input placeholder="Spieler, Verein oder Position suchen…" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={shortOnly} onChange={e=>setShortOnly(e.target.checked)}/> Nur Shortlist</label><span>{filtered.length} Spieler</span></div>{players.length?<PlayerTable players={filtered} onToggle={toggle} onDecision={decide}/>:<Empty onImport={()=>importData('targets')}/>}</section>}
 {tab==='squad'&&<section className="panel"><h2>Eigener Kader</h2>{squad.length?<><div className="squadGrid">{groups.map(g=><div className="squadCard" key={g.position}><span>{g.position}</span><b className={scoreClass(g.avg)}>{g.avg}</b><small>{g.count} Spieler</small></div>)}</div><PlayerTable players={squad} onToggle={()=>{}} onDecision={decide} hideShortlist/></>:<Empty squad onImport={()=>importData('squad')}/>}</section>}
 {tab==='settings'&&<section className="panel settings"><h2>Club Constraints</h2><label>Transferbudget (€)<input min="0" type="number" value={settings.transferBudget} onChange={e=>setSettings({...settings,transferBudget:Number(e.target.value)})}/></label><label>Max. Wochengehalt (€)<input min="0" type="number" value={settings.maxWeeklyWage} onChange={e=>setSettings({...settings,maxWeeklyWage:Number(e.target.value)})}/></label><label>Formation<input maxLength={30} value={settings.formation} onChange={e=>setSettings({...settings,formation:e.target.value})}/></label><div><button disabled={busy} className="primary" onClick={saveClub}>Speichern</button> <button disabled={busy} onClick={backup}>Datenbank-Backup</button></div></section>}</main>
 {decision&&<div className="modalBack" onClick={()=>setDecision(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDecision(null)}>×</button><small>TRANSFER DECISION</small><h2>{decision.player.name}</h2><div className={`verdict ${decision.data.verdict.toLowerCase()}`}>{decision.data.verdict}</div><div className="decisionGrid"><Card title="Moneyball" value={String(decision.player.scores.moneyball)} sub={`Confidence ${decision.player.scores.confidence}`}/><Card title="Max. Bid" value={money(decision.data.maxBid)} sub="Obergrenze"/><Card title="Max. Wage" value={money(decision.data.maxWage)} sub="pro Woche"/><Card title="1. Jahr" value={money(decision.data.firstYearCost)} sub="Ablöse + Gehalt"/></div><h3>Dafür</h3><p>{decision.data.reasons.join(' · ')||'Kein klarer positiver Trigger.'}</p><h3>Risiken</h3><p>{decision.data.risks.join(' · ')||'Keine unmittelbaren Warnungen.'}</p></div></div>}</div>
}
